### ISSUE TITLE
globalConfig.json schema accepts invalid configuration

### ISSUE THREAD

**Issue by arys-splunk** [splunk/addonfactory-ucc-base-ui#37]
This issue is a follow-up issue from https://github.com/splunk/addonfactory-ucc-generator/issues/210.

When creating an add-on using `ucc-gen` (version 5.0.0) command, it uses schema from this repository to validate globalConfig.json.

If I use globalConfig.json without "inputs" section - it should not be valid.

Example config: https://github.com/splunk/addonfactory-ucc-generator/files/6583733/globalConfig_1.txt

**Comment by arys-splunk** [comment]
@harshpatel-crest feel free to reassign it to appropriate person.

**Comment by arys-splunk** [comment]
@harshpatel-crest in https://github.com/splunk/addonfactory-ucc-base-ui/pull/39 you fixed it from the UI perspective. Can we also include a fix to the schema itself? So, we you are creating an add-on using `ucc-gen`, the schema validation will not pass.

**Comment by harshpatel-crest** [comment]
@arys-splunk This will allow loading UI without inputs page. We do support only configuration page globalConfigs in UCC. We have not made any changes to schema.

**Comment by arys-splunk** [comment]
That makes sense. Closing this one. Thanks for explanation.
