### ISSUE TITLE
Create "Search internal logs" button

### ISSUE THREAD

**Issue by hsekowski-splunk** [splunk/addonfactory-ucc-base-ui#370]
Create "Search internal logs" button.
The button will be available for each input.
Once used (clicked), new window will be opened with search application and applied search query 
index = _* source = *[input name]*

**Comment by hsekowski-splunk** [comment]
https://github.com/splunk/addonfactory-ucc-base-ui/tree/feature/search_internal_logs_button branch created

**Comment by artemrys** [comment]
I think it was already relesed.
