### ISSUE TITLE
pages > configuration > tabs > table > actions list ignored

### ISSUE THREAD

**Issue by hsekowski-splunk** [splunk/addonfactory-ucc-base-ui#74]
The default list is
"actions": [
                            "edit",
                            "delete",
                            "clone"
                        ]
I wanted to have only "delete" , but once I removed other, UI showed them as well. They worked also.
I did one more test - get rid of all options, but were still getting all of them in UI
![image (14)](https://user-images.githubusercontent.com/74253926/132345471-e81180be-6148-401e-bb3b-195d4dcfa962.png)
![image (15)](https://user-images.githubusercontent.com/74253926/132345501-2f0c8129-7d12-4a7a-927b-cdb73516167c.png)

**Comment by artemrys** [comment]
This will be fixed in the upcoming release by #239.

**Comment by artemrys** [comment]
Fixed in `ucc-gen` `v5.20.0`.
